"""Final

Revision ID: d53ed2d2f547
Revises: 1be94e8acb6e
Create Date: 2024-03-04 16:17:18.203956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d53ed2d2f547"
down_revision = "1be94e8acb6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
